/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PB_TEMP_PB_H_INCLUDED
#define PB_PB_TEMP_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _pb_TempEvent {
    uint32_t deviceId;
    uint32_t timestamp;
    bool status;
    float temp;
    float humidity;
    uint32_t batteryLevel;
} pb_TempEvent;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define pb_TempEvent_init_default                {0, 0, 0, 0, 0, 0}
#define pb_TempEvent_init_zero                   {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define pb_TempEvent_deviceId_tag                1
#define pb_TempEvent_timestamp_tag               2
#define pb_TempEvent_status_tag                  3
#define pb_TempEvent_temp_tag                    4
#define pb_TempEvent_humidity_tag                5
#define pb_TempEvent_batteryLevel_tag            6

/* Struct field encoding specification for nanopb */
#define pb_TempEvent_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   deviceId,          1) \
X(a, STATIC,   REQUIRED, UINT32,   timestamp,         2) \
X(a, STATIC,   REQUIRED, BOOL,     status,            3) \
X(a, STATIC,   REQUIRED, FLOAT,    temp,              4) \
X(a, STATIC,   REQUIRED, FLOAT,    humidity,          5) \
X(a, STATIC,   REQUIRED, UINT32,   batteryLevel,      6)
#define pb_TempEvent_CALLBACK NULL
#define pb_TempEvent_DEFAULT NULL

extern const pb_msgdesc_t pb_TempEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define pb_TempEvent_fields &pb_TempEvent_msg

/* Maximum encoded size of messages (where known) */
#define PB_TEMP_PB_H_MAX_SIZE                    pb_TempEvent_size
#define pb_TempEvent_size                        30

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
